### ISSUE TITLE
kicad 5.1版本

### ISSUE THREAD

**Issue by huexpub** [xtoolbox/lc_kicad_lib#1]
kicad 5.1版本，报错，库文件只能导入电容，MCU等

**Comment by haiwuxing** [comment]
kicad 5.1版本，报错，库文件只能导入电容，MCU等

### 期望结果
电路图中可以添加立创 电阻 等符号

### 实际结果
电路图中不能添加立创 电阻等符号。弹出如下提示：
![image](https://user-images.githubusercontent.com/6026869/55929584-fa1eb900-5c4f-11e9-8c7b-85fd6cd58c76.png)

```
11:44:35: 加载符号库lc_IC出现错误

invalid pin definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_IC.lib'
行数：73，偏移：2
11:44:35: 加载符号库lc_IUD出现错误

invalid symbol definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_IUD.lib'
行数：6，偏移：4
11:44:35: 加载符号库lc_LED出现错误

invalid symbol definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_LED.lib'
行数：6，偏移：4
11:44:35: 加载符号库lc_MOS出现错误

invalid symbol definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_MOS.lib'
行数：6，偏移：4
11:44:35: 加载符号库lc_RES出现错误

invalid symbol definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_RES.lib'
行数：6，偏移：4
11:44:35: 加载符号库lc_Transistor_NPN出现错误

invalid symbol definition在输入/源
'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_Transistor_NPN.lib'
行数：6，偏移：4
```

**Comment by xtoolbox** [comment]
因为库中有非ASCII字符，将库格式转换成UTF8就可以了

**Comment by xtoolbox** [comment]
> kicad 5.1版本，报错，库文件只能导入电容，MCU等
> 
> ### 期望结果
> 电路图中可以添加立创 电阻 等符号
> 
> ### 实际结果
> 电路图中不能添加立创 电阻等符号。弹出如下提示：
> ![image](https://user-images.githubusercontent.com/6026869/55929584-fa1eb900-5c4f-11e9-8c7b-85fd6cd58c76.png)
> 
> ```
> 11:44:35: 加载符号库lc_IC出现错误
> 
> invalid pin definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_IC.lib'
> 行数：73，偏移：2
> 11:44:35: 加载符号库lc_IUD出现错误
> 
> invalid symbol definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_IUD.lib'
> 行数：6，偏移：4
> 11:44:35: 加载符号库lc_LED出现错误
> 
> invalid symbol definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_LED.lib'
> 行数：6，偏移：4
> 11:44:35: 加载符号库lc_MOS出现错误
> 
> invalid symbol definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_MOS.lib'
> 行数：6，偏移：4
> 11:44:35: 加载符号库lc_RES出现错误
> 
> invalid symbol definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_RES.lib'
> 行数：6，偏移：4
> 11:44:35: 加载符号库lc_Transistor_NPN出现错误
> 
> invalid symbol definition在输入/源
> 'C:\Works\Demo\KiCad\ImportLiChuangDemo\lc_kicad_lib-master\lc_Transistor_NPN.lib'
> 行数：6，偏移：4
> ```

此问题已经修复，请测试没问题后关闭

**Comment by haiwuxing** [comment]
经测试，已经可以导入电阻等符号，请 @huexpub 测试OK后，关闭此问题
